### ISSUE TITLE
Image display wrongly displayed

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#1]
I have reduced the image sizes but are still struggling to have them displayed the right way. Shouldn't they adjust to the size i've added to the class item?

https://github.com/lenmarbra/lenmarbra.github.io/blob/7cd1b60726bcd1563f652c7c618d9878e861a6db/portfolio.css#L16

**Comment by lenmarbra** [comment]
@gorazd  see above

**Comment by gorazd** [comment]
The easiest way to achieve this is to put the images in the CSS as background images.

```css
.wrapper .item-1 {
  background-image: url(image.jpg);
  background-position: center;
  background-size: cover;
}
```
